apiVersion: v1
kind: Service
metadata:
  name: api-hospital-service
  namespace: jjs
spec:
  selector:
    app: api-hospital   # Deployment와 일치해야 함!
  ports:
    - protocol: TCP
      port: 8080        # 클러스터 내부 서비스 포트
      targetPort: 8080  # 컨테이너 포트
  type: NodePort
